services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: umbrella_broker
    ports:
      - "5672:5672"   # AMQP Protokoll
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: secret  